### ISSUE TITLE
EOL of ros kinetic 

### ISSUE THREAD

**Issue by tongtybj** [JSKAerialRobot/aerial_robot#463]
ROS kinetic distribution is almost (already?) end-of-life (EOL), because EOL of ubuntu 16.04 (Xenial)
Please check http://wiki.ros.org/Distributions.

I am thinking to stop supporting kinetic for this repository, and remove kinetic from CI list. 
@chibi314  How do you think?

BTW,  Eigen3 incompatible version problem occurs in kinetic: 
https://travis-ci.com/github/JSKAerialRobot/aerial_robot/jobs/499448902

**Comment by chibi314** [comment]
I agree. We shouldn't use ubuntu 16.04/ros kinetic now.

**Comment by tongtybj** [comment]
I still want to support kinetic following Kei Okada's policy
