### ISSUE TITLE
High load of mocap node

### ISSUE THREAD

**Issue by tongtybj** [JSKAerialRobot/aerial_robot#466]
@chibi314 

I have solved the problem of high load of mocap_node:
https://github.com/ros-drivers/mocap_optitrack/pull/62

I hope this PR would be merged. Before that, let's use [this patch branch](https://github.com/tongtybj/mocap_optitrack/tree/while_func_bug_debug).

**Comment by tongtybj** [comment]
https://github.com/ros-drivers/mocap_optitrack/pull/62 is merged, and the developer has update the version to [0.1.3](https://github.com/ros-drivers/mocap_optitrack/commits/master)
We still need to wait for the debian package for several weeks, I guess.

Let's manually install `mocap_optitrack` from source for  the coming several weeks.

**Comment by chibi314** [comment]
@tongtybj 
Should we close this PR?
https://github.com/JSKAerialRobot/aerial_robot_demo/pull/169
